using System;
using System.Collections.Generic;

namespace CorpusStudio.Desktop.Services;

/// <summary>Shared, pure knowledge of the Corpus Studio workspace layout: which top-level
/// directories hold generated artifacts (opened read-only), which files are dataset-core
/// (single-writer), and which directory names the explorer ignores. No I/O — used by both
/// the explorer and document services so they always agree.</summary>
public static class WorkspaceLayout
{
    /// <summary>Top-level directory names whose contents are generated by the engine and
    /// open read-only by default.</summary>
    public static readonly IReadOnlySet<string> GeneratedDirectories =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "reports", "training_runs", "model_artifacts", "dataset_versions",
            "evaluation_reports", "arena_reports",
        };

    /// <summary>Directory names skipped when building the tree (VCS / build / OS junk).
    /// The workspace's own ".corpus" metadata directory is intentionally NOT ignored.</summary>
    public static readonly IReadOnlySet<string> IgnoredDirectories =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".git", ".hg", ".svn", ".vs", ".idea", "node_modules", "__pycache__", "bin", "obj",
        };

    private static readonly IReadOnlySet<string> CoreFiles =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "examples.jsonl", ".corpus/project.json",
        };

    /// <summary>Normalize a workspace-relative path to forward slashes with surrounding
    /// separators trimmed.</summary>
    public static string Normalize(string relativePath) =>
        (relativePath ?? string.Empty).Replace('\\', '/').Trim('/');

    /// <summary>True when a relative path sits inside a generated-artifact directory.</summary>
    public static bool IsGeneratedArtifact(string relativePath)
    {
        var norm = Normalize(relativePath);
        if (norm.Length == 0) return false;
        var top = norm.Split('/')[0];
        return GeneratedDirectories.Contains(top);
    }

    /// <summary>True for examples.jsonl and the manifest.</summary>
    public static bool IsDatasetCoreFile(string relativePath) =>
        CoreFiles.Contains(Normalize(relativePath));

    public static bool IsIgnoredDirectory(string name) => IgnoredDirectories.Contains(name);
}
