"""`export --check-provenance`: the per-row provenance gate as a hard EXPORT enforcement
point — refuse to write a training deliverable that contains rows generated by a provider
you can't train on (the licensing counterpart to the PII export gate)."""

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from corpus_studio.cli import app

runner = CliRunner()


def _write(path: Path, rows: list[dict]) -> None:
    path.write_text(
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows),
        encoding="utf-8",
    )


def _instruction(output: str, teacher: str | None = None) -> dict:
    row: dict = {"instruction": "Explain a concept.", "output": output}
    if teacher is not None:
        row["meta"] = {"teacher": teacher}
    return row


@pytest.mark.parametrize("teacher", ["claude-opus-4-8", "gemini-2.5-pro"])
def test_check_provenance_blocks_on_restricted_teacher(tmp_path: Path, teacher: str):
    src = tmp_path / "rows.jsonl"
    _write(src, [_instruction("A.", teacher=teacher)])
    out = tmp_path / "export.jsonl"

    result = runner.invoke(
        app, ["export", str(src), str(out), "instruction", "--check-provenance"]
    )

    assert result.exit_code == 2, result.output
    assert "provenance gate" in result.output.lower()
    assert not out.exists()  # nothing written on a BLOCK


def test_allow_teacher_unblocks_and_records_pass(tmp_path: Path):
    src = tmp_path / "rows.jsonl"
    _write(src, [_instruction("A.", teacher="z-ai/glm-5.2")])
    out = tmp_path / "export.jsonl"

    result = runner.invoke(
        app,
        [
            "export", str(src), str(out), "instruction",
            "--check-provenance", "--allow-teacher", "z-ai/glm-5.2",
        ],
    )

    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    assert payload["provenance_checked"] is True
    assert payload["provenance_status"] == "pass"
    assert payload["quarantined_rows"] == 0
    assert out.exists()


def test_unknown_provenance_warns_but_proceeds(tmp_path: Path):
    src = tmp_path / "rows.jsonl"
    _write(src, [_instruction("A.")])  # no meta.teacher → unknown
    out = tmp_path / "export.jsonl"

    result = runner.invoke(
        app, ["export", str(src), str(out), "instruction", "--check-provenance"]
    )

    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    assert payload["provenance_status"] == "warn"
    assert payload["unknown_provenance_rows"] == 1
    assert any("provenance" in warning.lower() for warning in payload["warnings"])
    assert out.exists()


def test_provenance_strict_blocks_unknown(tmp_path: Path):
    src = tmp_path / "rows.jsonl"
    _write(src, [_instruction("A.")])
    out = tmp_path / "export.jsonl"

    result = runner.invoke(
        app,
        ["export", str(src), str(out), "instruction", "--check-provenance", "--provenance-strict"],
    )

    assert result.exit_code == 2, result.output
    assert not out.exists()


def test_without_the_flag_export_is_unchanged(tmp_path: Path):
    # A restricted-teacher row exports fine when the check is OFF — the gate is strictly opt-in,
    # and the payload carries no provenance keys (backward compatible).
    src = tmp_path / "rows.jsonl"
    _write(src, [_instruction("A.", teacher="claude-opus-4-8")])
    out = tmp_path / "export.jsonl"

    result = runner.invoke(app, ["export", str(src), str(out), "instruction"])

    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    assert "provenance_checked" not in payload
    assert "provenance_status" not in payload
    assert out.exists()


def test_project_allowlist_file_next_to_input_is_honored(tmp_path: Path):
    # A provenance_allowlist.json sitting beside the input (the project dir) clears a teacher
    # without needing a --allow-teacher flag.
    (tmp_path / "provenance_allowlist.json").write_text(
        json.dumps({"z-ai/glm-5.2": "MIT"}), encoding="utf-8"
    )
    src = tmp_path / "rows.jsonl"
    _write(src, [_instruction("A.", teacher="z-ai/glm-5.2")])
    out = tmp_path / "export.jsonl"

    result = runner.invoke(
        app, ["export", str(src), str(out), "instruction", "--check-provenance"]
    )

    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    assert payload["provenance_status"] == "pass"
    assert out.exists()
